name = "chat"
version = "1.0.0"

[dependencies]
baton = { path = "../../" }
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
gleam_stdlib = "0.38.0"
mist = ">= 1.0.0 and < 2.0.0"
wisp = ">= 0.14.0 and < 1.0.0"
stratus = ">= 0.9.0 and < 1.0.0"
repeatedly = ">= 2.1.1 and < 3.0.0"

